kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: siacdn-persistent-volume-claim
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi