apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: siacdn-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: siacdn-ip-address
    networking.gke.io/managed-certificates: siacdn-certificate
spec:
  backend:
    serviceName: siacdn-nodeport-service
    servicePort: 80